add getters to private properties, re: #148
zenstruck/browser pull request #150
Opened 2024-06-10 11:29 UTC by tacman

so the user can do something with the saved screenshots.

2024-07-21 11:06 UTC, tacman commented
Can you accept this PR, or give me some guidance on how to improve it?  Thx.

2024-07-21 17:00 UTC, nikophil requested changes

2024-07-21 17:00 UTC, nikophil commented on src/Browser/PantherBrowser.php
> +    }
I don't think we want to mutate these ones, WDYT @kbond?

2024-07-21 17:00 UTC, nikophil commented on src/Browser/PantherBrowser.php
> +    }
maybe i'ts time to bump php 8.1, and change these two properties to `public readonly`?

unfortunately, we can't do this for `savedScreenshots` / `savedConsoleLogs`... I really hope https://wiki.php.net/rfc/asymmetric-visibility-v2 will land in PHP some day :crossed_fingers:

2024-07-21 17:00 UTC, nikophil commented on src/Browser/PantherBrowser.php
> +    public function getSavedScreenshots(): array
```suggestion
    /**
     * @return list<string>
     */
    public function getSavedScreenshots(): array
```
(same below)

2024-07-21 17:37 UTC, nikophil commented on tests/PantherBrowserTest.php
> +        assert($this->browser()->getScreenshotDir() === $screenshotDir);
please, use `self::assertSame()`

2024-07-24 18:46 UTC, kbond commented
@tacman, you can't use the `BROWSER_SCREENSHOT_DIR` env var?

I think it would be better to update HasBrowser::pantherBrowser() to accept these as options (I don't think the following works right now):

```php
$this->pantherBrowser(['screenshot_dir' => 'some/dir']);
```

I'm really trying to keep the public api of browsers confined to just actions/assertions if possible.

2026-08-11 15:37 UTC, kbond commented
I'm going to close as stale for now. Feel free to reopen!

2026-08-11 15:37 UTC, closed without merging